[tool.poetry]
name = "repl_python3_Burg-Nurg"
version = "0.1.0"
description = ""
authors = ["benethicc <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pyttk = "^0.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
